### ISSUE TITLE
Typescript PeerDep

### ISSUE THREAD

**Issue by MathisTLD** [typescript-rtti/typescript-rtti#83] opened 2022-07-21 06:01 UTC
Would it be possible to bump typescript's peerDep version to latest ?
I'll do it myself if you we are supposed to contribute

Thanks for everything

**Comment by rezonant** [comment] 2022-07-21 20:44
Duplicate of #82. 4.7 has some larger changes that will require refactoring to support.

**Closed by rezonant** 2022-07-21 20:44 UTC
