### ISSUE TITLE
Type has kind any, expected interface

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#36] opened 2022-03-18 14:23 UTC
```typescript
import IMovable from './command/move/IMovable';

console.log(reflect<IMovable>().as('interface').reflectedInterface)
```

file IMovable.ts

```typescript
export default interface IMovable {
	position: Array<number>
	readonly movementVelocity: Array<number>
}
```

error

```
reflect.ts:321 Uncaught TypeError: Type has kind any, expected interface
    at ReflectedAnyRef.as (reflect.ts:321:36)
    at Object.h7u1C.reflect-metadata (index.ts:31:90)
    at newRequire (index.b71e74eb.js:71:24)
    at index.b71e74eb.js:122:5
    at index.b71e74eb.js:145:3
```

**Comment by rezonant** [comment] 2022-03-19 09:51
Confirmed, we'll work on a fix!

**Comment by rezonant** [comment] 2022-03-19 10:57
Cause: When an interface is exported as default, RTTI correctly requests the default export when importing the interface for the type reference. However, there will be no such default export in the resulting JS for the interface file, only an export for `IΦIMovable`. In the case where an interface is default exported, RTTI should export the interface token as `IΦdefault` not `IΦIMovable`, and when importing a known interface references, RTTI should request the `IΦdefault` export instead of `default` while retaining the `default` import for known class references

**Comment by rezonant** [comment] 2022-03-19 11:05
Note that I forgot to adjust the import path in the test case-- if you are getting `any` instead of something like "Reference is type 'literal", expected 'interface'" then this sounds like Typescript could not read the interface file while compiling the  referencing file. Most obvious cause would be an incorrect file path on the import. Otherwise, is there perhaps more to the original case in your codebase? For instance, is the interface perhaps dependent on types of the referencing file (ie circular reference?)

**Comment by rezonant** [comment] 2022-03-19 12:56
Fix for this issue released in `v0.5.1`. Please try it out and let us know if this particular issue is still a problem. Note that your other issue (#35) is still outstanding.

**Comment by khusamov** [comment] 2022-03-26 15:31
"typescript-rtti": "^0.5.3"

Sorry for the delay in answering! I installed the latest version. The error remains!

**Comment by rezonant** [comment] 2022-03-29 04:43
@khusamov I assume this is just because of the rollup issue (#46)- if you still encounter this issue outside of rollup, please reopen this issue

**Closed by rezonant** 2022-03-29 04:43 UTC
Labels: bug

**Comment by khusamov** [comment] 2022-03-29 05:54
"typescript-rtti": "^0.5.4"

I installed the latest version. The error remains!

**Comment by rezonant** [comment] 2022-03-29 06:14
Please create a reproduction then, as your other reproduction using rollup works correctly with 0.5.4

**Comment by khusamov** [comment] 2022-03-29 10:12
https://github.com/khusamov/temp-typescript-rtti-issue-36

**Comment by rezonant** [comment] 2022-03-29 16:59
Ah OK, this is expected behavior, see the README about Parcel. It cannot work unless Parcel implements Typescript compilation correctly. Parcel compiles each file individually without any type checking, and the transformer cannot work without both type checking and compiling all files together in the unit, like tsc, rollup, webpack, and most other integrations already do.
