### ISSUE TITLE
Cannot read properties of undefined (reading 'flags') when using Parcel

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#35] opened 2022-03-18 13:09 UTC
> Reproduction: https://github.com/khusamov/temp-typescript-rtti-issue-35
> Summary: Parcel introduces unexpected incompatibility

```
console: RTTI: During outboard metadata collection for class IoC: 
Cannot read properties of undefined (reading 'flags')


console: RTTI: Failed to build source file src/IoC.ts: Cannot read
properties of undefined (reading 'flags') [please report]


Error: Cannot read properties of undefined (reading 'flags')

```

The code of file `IoC.ts`:

```typescript

export default class IoC {
	static resolve(a: string[]): number {
		return 0
	}
}

IoC.resolve(['text'])

```

**Comment by khusamov** [comment] 2022-03-18 13:16
Here is an abbreviated example. The error is the same.

```typescript
class IoC {
	static resolve<T>(dependencyName: string, ...args: any[]): T {
		return {} as T
	}
}

Class1.resolve('dependencyName', () => {})
```

**Comment by rezonant** [comment] 2022-03-19 09:41
A cursory run of this code within the test environment does not show a failure. The cause of the failure may be related to your `tsconfig` configuration or some other aspect of your codebase that isn't replicated here.

**Comment by khusamov** [comment] 2022-03-19 10:28
```json
{
	"compilerOptions": {
		"moduleResolution": "Node",
		"module": "ES2020",
		"target": "ES2020",
		"strict": true,
		"removeComments": true,
		"sourceMap": true,
		"experimentalDecorators": true,
		"plugins": [
			{
				"transform": "typescript-rtti/dist/transformer"
			}
		]
	},
	"reflection": {
		"metadata": false,
		"debugMode": false
	}
}

```

```json
{
  "dependencies": {
    "ttypescript": "^1.5.13",
    "typescript": "^4.5.5",
    "reflect-metadata": "^0.1.13",
    "tst-reflect": "^0.7.4",
    "typescript-rtti": "^0.5.0"
  }
}
```

**Comment by khusamov** [comment] 2022-03-19 10:32
This code is not handled correctly:

```typescript

export default class IoC {
	static resolve(a: string[]): number {
		return 0
	}
}

IoC.resolve(['text'])

```

I changed the definition of the array:

`a: string[]` -> `a: Array<string>`

```typescript

export default class IoC {
	static resolve(a: Array<string>): number {
		return 0
	}
}

IoC.resolve(['text'])

```

In this case, the error has disappeared!

**Comment by rezonant** [comment] 2022-03-19 10:35
What is your library setting in tsconfig? This sounds like #33

**Comment by khusamov** [comment] 2022-03-19 10:37
```json
{
	"compilerOptions": {
		"moduleResolution": "Node",
		"module": "ES2020",
		"target": "ES2020",
		"strict": true,
		"removeComments": true,
		"sourceMap": true,
		"experimentalDecorators": true,
		"plugins": [
			{
				"transform": "typescript-rtti/dist/transformer"
			}
		]
	},
	"reflection": {
		"metadata": false,
		"debugMode": false
	}
}

```

**Comment by rezonant** [comment] 2022-03-19 10:45
Hmm, using those compilerOptions in test is green as well. There must be another cause as to why this happens-- in the quoted discussion, it was indicated they were also not using `noLib`.

**Comment by rezonant** [comment] 2022-03-19 10:45
Could you try to make a reproduction repository for this?

**Comment by khusamov** [comment] 2022-03-19 10:46
Yes, I will make a separate repository with this error later.

**Comment by khusamov** [comment] 2022-03-19 11:03
https://github.com/khusamov/temp-typescript-rtti-issue-35

**Comment by rezonant** [comment] 2022-03-19 19:33
Parcel is indeed compiling your TS using `noLib`, very curious.

![image](https://user-images.githubusercontent.com/409140/159135737-82d0954f-4a61-43f0-9be3-3a0ffac342fa.png)

**Comment by rezonant** [comment] 2022-03-19 20:03
OK so here's the situation. The `parcel-transformer-ttypescript` plugin you are using is using `typescript.transpileModule()`. When that method is used to transpile a single file, `noLib` is always set to true. This is not specific to that transformer. Parcel's own Typescript support does this too: https://parceljs.org/languages/typescript/#isolatedmodules

Unfortunately, I don't see a way to make it remotely possible to do RTTI when processing files individually, as RTTI _by definition_ requires the ability to introspect types across files just like your IDE and tsc (when run in a normal fashion). 

I'm not too familiar with Parcel, but if there were a transformer that was able to compile all your Typescript in a single compilation unit that should resolve this issue.

**Comment by rezonant** [comment] 2022-03-19 20:16
There's going to be a lot to fall out from this issue, both documentation changes and a wider project to improve this situation (likely finding or creating a "proper" typescript transformer for parcel) but in the mean time, this thread and comment may be useful to work around this issue as the cause of their problem is the same as yours 

https://github.com/parcel-bundler/parcel/issues/3645#issuecomment-542309714

**Comment by rezonant** [comment] 2022-03-19 22:23
I have updated documentation to note this limitation and also made some improvements to work around when `noLib` is used (as in Parcel) as well as some developer experience improvements here, ensuring that we never crash in this scenario and print a useful error message:

```
RTTI: main.ts: [Return type of method method() of class C] Missing symbol for type with flags=524288 without type node! 'Object' will be emitted for the type instead.
RTTI: ^-- You are compiling with noLib enabled, which may interfere with inferred array types. You may be able to work around this issue by explicitly declaring the array type instead of relying on inference. This notice is shown only once.
```

These will be in the next release. This may be useful to you if the "build ahead with TSC" workaround is unsuitable for your use case.

**Comment by rezonant** [comment] 2022-03-29 04:41
Since Parcel would need to implement proper TS compilation for this to work and there isn't any outstanding RTTI-side bugs here, I'm going to close this.

**Closed by rezonant** 2022-03-29 04:41 UTC
Labels: bug

**Comment by khusamov** [comment] 2022-03-29 10:13
This error seems to have been fixed. No longer playable!
