### ISSUE TITLE
Bug: Properties of function type return any

### ISSUE THREAD

**Issue by Wyctus** [typescript-rtti/typescript-rtti#67] opened 2022-06-03 23:24 UTC
I have a class like this:

```typescript
class A {
	a: (arg1: string, arg2: boolean) => number;
}
```

I would like to get the arguments and the return type of such a function-type property.
I couldn't find anything, is there any way to do this?

Thank you!

**Comment by rezonant** [comment] 2022-06-04 02:37
`reflect(A).getMethod('a')`

Use:
- .returnType
- .parameters(.type)

**Comment by rezonant** [comment] 2022-06-04 02:50
This is a bug, see: https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7XG5cbmNsYXNzIEEge1xuICAgIGZvbyA9ICgpID0+IHsgcmV0dXJuIHRydWUgPyAxMjMgOiAnZm9vJzsgfVxufVxuXG5jb25zb2xlLmxvZyhyZWZsZWN0KEEpLmdldE1ldGhvZCgnZm9vJykucmV0dXJuVHlwZSk7IiwiY29tcGlsZXJPcHRpb25zIjoiIn0=

The type ends up as `any` despite a local resolution for the type definition:

```javascript

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const __RΦ = { m: (k, v) => (t, ...a) => t && Reflect.metadata ? Reflect.metadata(k, v)(t, ...a) : void 0, f: (f, d, n) => (d.forEach(d => d(f)), Object.defineProperty(f, "name", { value: n, writable: false }), f), c: (c, d, dp, dsp, n) => (d.forEach(d => d(c)), dp.forEach(([p, d]) => d(c.prototype, p)), dsp.forEach(([p, d]) => d(c, p)), n ? Object.defineProperty(c, "name", { value: n, writable: false }) : undefined, c), r: (o, a) => (Object.assign(o, a)), a: id => {
        let t = __RΦ.t[id];
        if (t === void 0)
            return void 0;
        if (t.RΦ) {
            let r = t.RΦ;
            delete t.RΦ;
            __RΦ.r(t, r(t));
        }
        else if (t.LΦ) {
            let l = t.LΦ();
            delete t.LΦ;
            __RΦ.t[id] = t = l;
        }
        return t;
    }, t: { [79]: { RΦ: t => ({ TΦ: "O", m: [{ n: "foo", f: "", t: __RΦ.a(84) }] }) }, [84]: { LΦ: t => Function }, [4]: { RΦ: t => ({ TΦ: "~" }) } } };
const typescript_rtti_1 = require("typescript-rtti");
class A {
    constructor() {
        this.foo = () => { return true ? 123 : 'foo'; };
    }
}
(t => __RΦ.t[80] = t)(A);
__RΦ.m("rt:SP", [])(A);
__RΦ.m("rt:P", ["foo"])(A);
__RΦ.m("rt:Sm", [])(A);
__RΦ.m("rt:m", [])(A);
__RΦ.m("rt:f", "C")(A);
__RΦ.m("rt:t", () => __RΦ.a(4))(A.prototype, "foo");
__RΦ.m("rt:f", "P")(A.prototype, "foo");
console.log((0, typescript_rtti_1.reflect)(A, { TΦ: "c", t: void 0, p: [__RΦ.a(79)], r: void 0, tp: [] }).getMethod('foo').returnType);

```

Of interest is: 

Type definition:
```javascript
 [4]: { RΦ: t => ({ TΦ: "~" }) } } } // "any" type (~)
```

And 

```javascript
__RΦ.m("rt:t", () => __RΦ.a(4))(A.prototype, "foo");
```

**Comment by Wyctus** [comment] 2022-06-04 09:11
@rezonant thank you for taking a look!

**Comment by Wyctus** [comment] 2022-06-04 12:49
Is there an expected date for this fix? I really like this library, but this bug forces me to write my own ts transformer plugin, which would require replicating a lot of things that already work perfectly with yours.

**Comment by rezonant** [comment] 2022-06-05 19:06
@Wyctus Support has been added in typescript-rtti@0.7.0.

> I really like this library, but this bug forces me to write my own ts transformer plugin, which would require replicating a lot of things that already work perfectly with yours.

That would be a lot of work! Have you considered submitting PRs here instead? I could definitely use some help in moving things forward as we find corner cases and missing functionality.

Since you've expressed interest in this feature, I thought you might like to review what it took to add this support, so I did this one as a PR for easy review: https://github.com/typescript-rtti/typescript-rtti/pull/68

To help you or anyone else understand how this library works a bit better, below is an annotated guide through the implementation process. It's not that tricky, I promise!

--

To get started, I used the Typescript AST Viewer to analyze how Typescript expressed this particular type: https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbzlApgMwDYoMbwL5xpQQhwDkMAnmCgM7ZTBgwC0sMwZA3AFA-YYAhrVpwAgoh5xphCBDgBeOAAoAlIoB8iZChgBXKADs4MKHpRwA-HACMAJgDMcAFzk0c7nDw9v-CIdoILAA6DAgAc2VUTBwYZTFVYPDdAAViGlhKZTJ3CDJEqhpVLiA

I then wrote a quick test in metadata.test.ts with our test snippet and set it to `it.only` so that I could easily debug into how typescript-rtti was currently handling this type. Support for debugging the test suite is built in to the repository if you are using VS Code. 

I then saw we had a bit of a deficiency when handling property types: It would only work for declared types (ie those that have a type annotation on them). I could see this as `typeNode` was undefined, which makes sense as that will only be present when there is a literal type annotation in the code.

That was fairly easy to fix:
![image](https://user-images.githubusercontent.com/409140/172065577-1753b416-a3cf-44f6-97d8-539c78d79724.png)

The MetadataEncoder class has a `typeNode()` helper which takes a ts.TypeNode and calls `type()` passing in both the type returned by the type checker for the given node, and the node itself (this is useful for many reasons deeper into the code).

From here, I was no longer getting `any` back, but instead the expected `Function`. However, this could be better, as obviously the desire is to reflect upon the function's return type and parameters. So at this point I headed into `format.ts` where all of the metadata format types live, so that I could add a new kind of RtRef (RtRefs are the objects which have ie `TΦ: '~'` indicators). I chose `F` to represent a function type ref, and constructed a new interface to represent this new kind of RtType

```typescript
export const T_FUNCTION: 'F' = 'F';

//...

export interface RtFunctionType {
    TΦ: typeof T_FUNCTION;
    r: RtType;
    p: RtParameter[];
    f: string;
}
```

Here the intent is for `r` to represent return type, `p` to represent the set of parameters, and I added `f` to hold a flags string, though there is so far no use of this (just there for future uses).

To add support for this new RtType, I needed to modify the `typeLiteral()` function. `typeLiteral()` is the core of metadata emitting, it is responsible for creating the Typescript AST nodes that represent a specific type (ignoring deduplication / indexing / lookups). A key thing to note is that `typeLiteral()` is only supposed to construct an AST fragment _for the particular type_ its being called for. If any other types are _referenced_ by that type, it is to use `encoder.referToType(type: ts.Type)` to do so. This allows the particular type encoder (which can be the legacy emitDecoratorMetadata encoder or the actual RTTI encoder) to handle indexing the types so that a given type is only emitted once for a given source file. The encoder is always passed into typeLiteral():

```typescript
export function typeLiteral(encoder: TypeEncoderImpl, type: ts.Type, typeNode?: ts.TypeNode, options?: TypeLiteralOptions);
```

As you can see, the previous behavior here was just to return an identifier token of `Function` so that the RtType would be the `Function` constructor. If you examine `RtType`, you'll see that it is valid for an RtType to be a constructor function among other things, that is how simple primitive (non-literal) types and classes are represented. 

The expansion here simply gets the call signatures for the particular type, warns out if its more than 1, and then proceeds to use the first signature to produce the new RtFunctionType. The `serialize()` method is a helper to take a literal POJO and turn it into a TS AST fragment that represents that POJO. However, the referToType() returns an AST node already, so the `literalNode` helper tells `serialize()` to skip encoding that value and simply pass it back as if it was a ts.Node (as it is).

![image](https://user-images.githubusercontent.com/409140/172066039-31190fc0-fd27-44e0-9ab8-acd5689fd7a3.png)

The warning is there to flag to any users that we're using only the first call signature, as there could be a scenario where that's possible, but some quick testing using TS AST Viewer showed that using `typeof foo` where foo is a function with multiple signatures and making an interface with two call signatures yielded a symbol which did not have the Function symbol flag, so I _think_ that warning will never get hit. 

A gotcha here is that `getTypeOfSymbolAtLocation()` really wants a valid node to determine the correct type of a Symbol, but if the `typeNode` is undefined, how do we do it for the paremeters which is an array of Symbols? The type encoder comes to the rescue here by exposing the RTTI "context" as `encoder.ctx`. From there, we can access the current "top level statement", which will be the statement which has the SourceFile as its parent which is currently being processed. This provides a suitable anchor for the type checker to determine the necessary ts.Type to return.

--

The last part was to add support for this new RtType within the reflection library (`reflect.ts`). The library uses decorators and some metaprogramming to avoid boilerplate. First, `'function'` needed to be added to the `ReflectedTypRefKind` union, and then an entry was added in the TYPE_REF_KIND_EXPANSION constant. That constant is used to map from the low-level RtType indicators (`~`, `F`, `|`, etc) to the high level "kind" names (`any`, `function`, `union`, etc). 

I then added a new ReflectedTypeRef subclass `ReflectedFunctionRef` annotated with `@ReflectedTypeRef.Kind('function')`. The decorator tells the library that when a plain `ReflectedTypeRef` is created which has `kind === 'function'` it should replace it with an instance of `ReflectedFunctionRef`. The underlying `RtType` can be found in the `ref` protected field. From here, I just added cached getters for the return type and parameters, and implemented the matches() and matchesValue() methods so that the type and value matching functionality works for these new type references.

In order to handle checking that a runtime function value matches the given ReflectedFunctionRef, I augmented the type of `matches()` to include `ReflectedFunction`, and then acquired the ReflectedFunction for the passed function, and passed it in:

```typescript
    protected override matches(ref : this | ReflectedFunction) {
        return this.returnType.equals(ref.returnType)
            && this.parameters.every((p, i) => p.equals(ref.parameters[i]))
            && this.flags.toString() === ref.flags.toString()
        ;
    }

    override matchesValue(value: any, errors?: Error[], context?: string): boolean {
        return this.matches(ReflectedFunction.for(value));
    }
```

I think that's pretty nice :-D

**Comment by rezonant** [comment] 2022-06-05 19:20
Hmm I think there's a bit of a mismatch though in the types for the `p` property, in the library I treat it as an RtProperty but in the emitter it comes out as an RtType. Will need to fix this in a patch release.

**Comment by rezonant** [comment] 2022-06-05 19:57
Should be fixed with https://github.com/typescript-rtti/typescript-rtti/commit/057edc8700b735020161c437287f608dedab993a as long as the corpus test suite is OK with it.

**Comment by rezonant** [comment] 2022-06-05 20:20
OK 0.7.1 is out with that fix. Let me know if you have any trouble with this and if you are up to it, we welcome PRs!

**Comment by Wyctus** [comment] 2022-06-05 21:05
@rezonant 
Wow, thank you for this really detailed example of implementing this!

We work on a GraphQL library and typescript-rtti looks like a good fit for our purposes, so it would be the easiest for both of us if we would contribute! I will take a look in a couple of days to understand more deeply. 

This new release works great with this: 
```ts
class A {
    foo = () => { return true ? 123 : 'foo'; }
}
```

But my original example was a little different. There is only a property with a function type:

```ts
class User {
  first_name!: string;
  last_name!: string;
  middle_name?: string;
  email!: string;
}

class UserQuery {
    user!: (id: number) => User;
}
```

My goal is to get the name and the types of the parameters and the return type.

**Comment by rezonant** [comment] 2022-06-05 21:40
Ooof yes it's going down an entirely different code path there, even though the intended code path does have support for this (thats when typeNode is _not_ undefined).

https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7XG5cbmNsYXNzIEEge1xuICAgIGZvbyA6ICgpID0+IHN0cmluZyB8IG51bWJlcjtcbn1cblxuY29uc29sZS5sb2cocmVmbGVjdChBKS5nZXRQcm9wZXJ0eSgnZm9vJykudHlwZSk7IiwiY29tcGlsZXJPcHRpb25zIjoiIn0=

**Comment by rezonant** [comment] 2022-06-05 21:41
Also @capaj is also working on an RTTI-capable GraphQL library with the in-progress version of Decapi https://github.com/capaj/decapi/tree/rtti-wip

Maybe you lot can join forces?

**Comment by rezonant** [comment] 2022-06-05 21:52
I think https://github.com/typescript-rtti/typescript-rtti/commit/c65f06c556af774c654d2500525a0436939e302b should do it.

https://app.circleci.com/pipelines/github/typescript-rtti/typescript-rtti/323/workflows/e2470485-dbe4-4f20-8f02-e64a58541c8a

**Comment by Wyctus** [comment] 2022-06-05 21:54
Yes, Decapi looks similar and we are also in the middle of a rewrite 😄
In our 1.x version we have a little too verbose syntax, we could simplify it a lot by using RTTI.

Our project is focused on SQL-based GraphQL APIs. First, we optimize the queries by directly generating SQL queries based on the GraphQL AST. Second, we provide auto-generated queries and mutations for the most common use cases like query unique element, many elements, delete, create, update, etc. 

It was originally an internal project, multiple backends use it in production, but finally we decided to open source it, so the documentation is currently lacking a "little bit", and we are also working on 2.x version, so we didn't spend time to extend it, we will write great documentation for the next version instead.
https://github.com/synth-labs/graphql-x

**Comment by Wyctus** [comment] 2022-06-05 22:27
Thank you 0.7.3 doesn't give `any` anymore.

For my previous example, `console.log(reflect(UserQuery).getProperty("user").type);` prints 
`ReflectedUnknownRef { _ref: { 'TΦ': 'U' } }`.

Could you show me an example of how can I get from this the return type and the arguments?

**Comment by CristianPi** [comment] 2022-06-24 21:44
@Wyctus 

there's a bug or a missing feature (FunctionType)
input
```typescript
class User {
  first_name!: string;
  last_name!: string;
  middle_name?: string;
  email!: string;
}
class UserQuery {
  user!: (id: number) => User;
}

console.log(999,"UserQuery",reflect(UserQuery).getProperty("user").type.kind);
//console output: 999 UserQuery object
```


```typescript

[33788]: { RΦ: t => ({ TΦ: "O", m: [{ n: "user", f: "", t: __RΦ.a(33789) }] }) },
//(id: number) => User ->  coded as an object?
[33789]: { RΦ: t => ({ TΦ: "O", m: [{ n: "__call", f: "", t: __RΦ.a(4) }] }) }


class User {
}
(t => __RΦ.t[33781] = t)(User);
__RΦ.m("rt:SP", [])(User);
__RΦ.m("rt:P", ["first_name", "last_name", "middle_name", "email"])(User);
__RΦ.m("rt:Sm", [])(User);
__RΦ.m("rt:m", [])(User);
__RΦ.m("rt:f", "C")(User);
__RΦ.m("rt:t", () => __RΦ.a(15))(User.prototype, "first_name");
__RΦ.m("rt:f", "P")(User.prototype, "first_name");
__RΦ.m("rt:t", () => __RΦ.a(15))(User.prototype, "last_name");
__RΦ.m("rt:f", "P")(User.prototype, "last_name");
__RΦ.m("rt:t", () => __RΦ.a(15))(User.prototype, "middle_name");
__RΦ.m("rt:f", "P?")(User.prototype, "middle_name");
__RΦ.m("rt:t", () => __RΦ.a(15))(User.prototype, "email");
__RΦ.m("rt:f", "P")(User.prototype, "email");
class UserQuery {
}
(t => __RΦ.t[33785] = t)(UserQuery);
__RΦ.m("rt:SP", [])(UserQuery);
__RΦ.m("rt:P", ["user"])(UserQuery);
__RΦ.m("rt:Sm", [])(UserQuery);
__RΦ.m("rt:m", [])(UserQuery);
__RΦ.m("rt:f", "C")(UserQuery);
__RΦ.m("rt:t", () => __RΦ.a(33789))(UserQuery.prototype, "user");
__RΦ.m("rt:f", "P")(UserQuery.prototype, "user");
console.log(999, "UserQuery", (0, typescript_rtti_1.reflect)(UserQuery, { TΦ: "c", t: void 0, p: [__RΦ.a(33788)], r: void 0, tp: [] }).getProperty("user").type.kind);

```

**Comment by Wyctus** [comment] 2022-06-25 13:29
@CristianPi 
Yes, seems like it, but I don't have the insight to find the bug.

**Comment by CristianPi** [comment] 2022-06-28 22:49
> @CristianPi Yes, seems like it, but I don't have the insight to find the bug.

One of these days i will have a look

**Comment by CristianPi** [comment] 2022-06-28 22:50
@Wyctus 
One of these days i will give it a shot

**Comment by Wyctus** [comment] 2022-06-29 10:19
@CristianPi 
Great, thank you!

**Comment by rezonant** [comment] 2022-12-24 09:27
This might have been fixed somewhat unintentionally? This playground appears to be working. Closing for now, will reopen if we have a new reproduction of the issue.

https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7XG5cbmNsYXNzIFVzZXIge1xuICBmaXJzdF9uYW1lITogc3RyaW5nO1xuICBsYXN0X25hbWUhOiBzdHJpbmc7XG4gIG1pZGRsZV9uYW1lPzogc3RyaW5nO1xuICBlbWFpbCE6IHN0cmluZztcbn1cbmNsYXNzIFVzZXJRdWVyeSB7XG4gIHVzZXIhOiAoaWQ6IG51bWJlcikgPT4gVXNlcjtcbn1cblxuY29uc29sZS5sb2coJ3R5cGUgb2YgVXNlclF1ZXJ5LnVzZXI6JywgcmVmbGVjdChVc2VyUXVlcnkpLmdldFByb3BlcnR5KFwidXNlclwiKS50eXBlLmtpbmQpO1xuY29uc29sZS5sb2coJ3R5cGUgb2YgcGFyYW1ldGVyIHRvIFVzZXJRdWVyeS51c2VyOicsIHJlZmxlY3QoVXNlclF1ZXJ5KS5nZXRQcm9wZXJ0eShcInVzZXJcIikudHlwZS5hcygnZnVuY3Rpb24nKS5wYXJhbWV0ZXJzWzBdLnR5cGUpOyIsImNvbXBpbGVyT3B0aW9ucyI6IiJ9

**Closed by rezonant** 2022-12-24 09:27 UTC
Labels: bug

**Comment by Wyctus** [comment] 2022-12-24 22:08
Yes, I can confirm it works now! Thanks!
